export const LOGIN_SUCESS="LOGIN_SUCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOG_OUT="LOGIN_OUT";
export const LOAD_PROFILE="LOAD_PROFILE";

export const HOME_VIDEOS_SUCESS="HOME_VIDEOS_SUCESS";
export const HOME_VIDEOS_FAIL="HOME_VIDEOS_FAIL";
export const HOME_VIDEOS_REQUEST="HOME_VIDHOME_VIDEOS_REQUEST";


export const SELECTED_VIDEOS_REQUEST="SELECTED_VIDEOS_REQUEST"
export const SELECTED_VIDEOS_SUCESS="SELECTED_VIDEOS_SUCESS"
export const SELECTED_VIDEOS_FAIL="SELECTED_VIDEOS_FAIL"


export const CHANNEL_DETAILS_REQUEST="CHANNEL_DETAILS_REQUEST"
export const CHANNEL_DETAILS_SUCESS="CHANNEL_DETAILS_SUCESS"
export const CHANNEL_DETAILS_FAIL="CHANNEL_DETAILS_FAIL"


export const SET_SUBSCRIPTION_STATUS="SET_SUBSCRIPTION_STATUS"


export const COMMENT_LIST_SUCESS="COMMENT_LIST_SUCESS"
export const COMMENT_LIST_REQUEST="COMMENT_LIST_REQUEST"
export const COMMENT_LIST_FAIL="COMMENT_LIST_FAIL"

export const RELATED_VIDEO_SUCESS="RELATED_VIDEO_SUCESS"
export const RELATED_VIDEO_REQUEST="RELATED_VIDEO_REQUEST"
export const RELATED_VIDEO_FAIL="RELATED_VIDEO_FAIL"